### PR TITLE
Add initial support for scaleway

### PR DESCRIPTION
**Pull request by elthariel**
This PR adds initial support for [Scaleway](https://www.scaleway.com/) _cloud_ provider.

I've currently only played with the `machine` resource, but afaict it works reasonably well. It's nice to be able to provision from chef !

There isn't any serious unit testing done on this new driver as there wasn't any other driver's tests to base my tests on. I'd be happy to had some with some guidance/examples

Signed-off-by: Julien 'Lta' BALLET <contact@lta.io>

### CODE REVIEW

**Comment by jjasghar** [comment]
WOW!

This is amazing, thanks for this. I'll give it a test here soon and then make any comments.

Thanks! 🤘

**Comment by elthariel** [comment]
I'm unable to make it work properly, I dig a bit in the code, but it gets pretty deep :)

If I do something like

```ruby
with_driver 'fog:Scaleway', compute_options: {scaleway_token: from_databag}
```

It won't work when destroying the node because the `machine_spec` has the canonical url but the `current_driver` is using the short url from the recipe.

It works if I use:

```ruby
with_driver 'fog:Scaleway:my-org-uuid', compute_options: {scaleway_token: from_databag}
```

Is the first form supposed to work ?

I was thinking about overriding `driver_url` in my driver to return the canonical url whenever possible, but I'm not even sure it'll work.

Any thoughts @jjasghar ?

**Comment by elthariel** [comment]
This would probably work if I was storing my credentials using fog, but I'd like to keep this in a secure databag

**Comment by elthariel** [comment]
I've created a `scaleway_volume` resource to handle volume allocation at scaleway. I've been thinking a little about something more generic that would allow to handle other providers like openstack block storage, but it thought it was a little bit premature. Let's make this work and promote it later to `fog_volume` or just `volume` if people are interested.

**Comment by elthariel** [comment]
Rebase, squash and sign-off

**Comment by elthariel** [comment]
cc @chef/provisioning

**Comment by elthariel** [comment]
Hey folks, a review would be really appreciated :)

**Comment by jjasghar** [comment]
@elthariel yep! I'm going to attempt to review this ASAP. (sorry i have a lag due to the holidays.)

**Comment by elthariel** [comment]
Oh yes, I forgot about thanksgiving and stuff :-/ I hope the stuffing was great and the turkey wasn't dry :)

**Comment by elthariel** [comment]
We're months beyond reasonable guys. That's likely going to be the last patch I send here.

**Comment by jjasghar** [comment]
I appologize with the delay. 

I'll merge it now, thanks for the patch!

**Pull request merged**
