### PR TITLE
Support for "no_network" by introduction of ssh_address_locations option

### PR DESCRIPTION
**Pull request by bdangit**
- [no_network is a valid option when there is no concept of
   floating_ips][1]
 - this flag supercedes any floating_ip operations as making
   fog to check on floating_ip would also raise exception
   and cause convergence to fail

[1]: http://git.io/vv96P

### CODE REVIEW

**Comment by jkeiser** [comment]
@bdangit is there any possibility we can just let the user specify the network they want to attach to in this case?  I am worried we may be making too many special-snowflake options when just one is all we need.

Also, what is the exception you receive when we check floating_ips?  It feels a bit like `find_floating_ips(server)` might be the right place to fix this.  (If it's an openstack-specific fix, you can override it in the openstack provider.)

**Comment by bdangit** [comment]
@jkeiser I'll have to get back to you on this question.  Unless @jjasghar could chime in again to help me understand `no-network` and `floating-ips`.  

Here is the exception that I get:

```
    Excon::Errors::Forbidden
    ------------------------
    Expected([200, 203]) <=> Actual(403 Forbidden)
    excon.error.request
      :chunk_size          => 1048576
      :ciphers             => "HIGH:!SSLv2:!aNULL:!eNULL:!3DES"
      :connect_timeout     => 60
      :debug_request       => true
      :debug_response      => true
      :expects             => [
        200
        203
      ]
      :headers             => {
        "Accept"       => "application/json"
        "Content-Type" => "application/json"
        "Host"         => ### REMOVED FROM VIEW ###
        "User-Agent"   => "fog/1.28.0 fog-core/1.29.0"
        "X-Auth-Token" => ### REMOVED FROM VIEW ###
      }
      :host                => ### REMOVED FROM VIEW ###
      :hostname            => ### REMOVED FROM VIEW ###
      :idempotent          => false
      :instrumentor_name   => "excon"
      :method              => "GET"
      :middlewares         => [
        Excon::Middleware::ResponseParser
        Excon::Middleware::Expects
        Excon::Middleware::Idempotent
        Excon::Middleware::Instrumentor
        Excon::Middleware::Mock
      ]
      :mock                => false
      :nonblock            => true
      :omit_default_port   => false
      :path                => "/v2/### REMOVED FROM VIEW ###/os-floating-ips.json"
      :persistent          => false
      :persistent          => false
      :port                => ### REMOVED FROM VIEW ###
      :query               => nil
      :read_timeout        => 60
      :retries_remaining   => 4
      :retry_limit         => 4
      :scheme              => "http"
      :ssl_verify_peer     => true
      :tcp_nodelay         => false
      :thread_safe_sockets => true
      :uri_parser          => URI
      :versions            => "excon/0.44.4 (x86_64-linux) ruby/2.1.4"
      :write_timeout       => 60
    excon.error.response
      :body          => "{\"forbidden\": {\"message\": \"Policy doesn't allow compute_extension:floating_ips to be performed.\", \"code\": 403}}"
      :headers       => {
        "Content-Length"       => "111"
        "Content-Type"         => "application/json; charset=UTF-8"
        "Date"                 => "Wed, 08 Apr 2015 07:24:55 GMT"
        "X-Compute-Request-Id" => ### REMOVED FROM VIEW ###
      }
      :local_address => ### REMOVED FROM VIEW ###
      :local_port    => ### REMOVED FROM VIEW ###
      :reason_phrase => "Forbidden"
      :remote_ip     => ### REMOVED FROM VIEW ###
      :status        => 403
```

I traced all the references whenever we try to tell fog to looking for a floating ip and I get an exception.  We probably could try to do a rescue case here and ask fog for the first ip address.  Then we wouldn't need a `--no-network` flag.  Perhaps may need to get a method speced out that is just `def get_ip` and it should return whatever ip address is required to ssh in.

**Comment by jjasghar** [comment]
@bdangit `floating-ips` are only useful if you have floating ips enabled. It'll blow up if you don't have it enabled or don't have access to it.

On your OpenStack cloud do you have floating ips?

**Comment by bdangit** [comment]
@jjasghar no floating ips what so ever.

**Comment by jjasghar** [comment]
This smells like something on the `fog` side. But honestly, I haven't dug into it. I can put it on my TODO if this isn't answered soon.

**Comment by bdangit** [comment]
Here was my analysis of what may be the problem with fog (or maybe not a problem with fog).

#all_addresses = sw limitation with current openstack api doesn't tell you floating ips vs fixed ips (it will attempt to look up floating ips).
https://github.com/fog/fog/blob/01202f61327392142fa3a28b2cda7f870199214e/lib/fog/openstack/models/compute/server.rb#L101-L106

#ip_addresses = makes no attempt to look up floating ips
ref: https://github.com/fog/fog/blob/01202f61327392142fa3a28b2cda7f870199214e/lib/fog/openstack/models/compute/server.rb#L113-L117

#private_ip_address (tries to look up all the floating ips)
ref: https://github.com/fog/fog/blob/01202f61327392142fa3a28b2cda7f870199214e/lib/fog/openstack/models/compute/server.rb#L146-L148


#public_ip_address (tries to look up all the floating ips)
ref: https://github.com/fog/fog/blob/01202f61327392142fa3a28b2cda7f870199214e/lib/fog/openstack/models/compute/server.rb#L146-L148

**Comment by bdangit** [comment]
@jkeiser / @jjasghar 

Looks like there is an open-ended issue with respect to this "floating-ips" 

https://github.com/fog/fog/issues/2160

Given all of this, I would expect chef-provisioning to abstract all of this into a method `converge_ip` whether it is floating, private, public, ghastly, interstellar, etc.  I suppose a more robust version of  `converge_floating_ips` that is provided.

**Comment by tyler-ball** [comment]
It seems like we keep adding different feature flags to support these available ways of finding the guest address.  Instead of multiple feature flags, why don't we have one option named `ssh_address_locations` that accepts an array of Strings, and defaults to `['public_ip_address', 'private_ip_address']`.  Provisioning will try and find an address using the methods provide and will stop on the first successful method.

This would allow users to specify `ssh_address_locations ['public_ip_address', 'private_ip_address', 'ip_addresses']` if floating IP addresses aren't available.  As part of this we would ensure that if the method errors or returns nothing, it is invalid.

**Comment by bdangit** [comment]
@tyler-ball are you suggesting that we get all the IPs possible, then just have a feature flag of whats the most preferred way to ssh in?

**Comment by tyler-ball** [comment]
Kind of -  I'm suggesting we have only 1 option the user specifies in the machine_options.  This config (`ssh_address_locations`) would expect to have an array of strings and would have a sane default.  Inside `create_ssh_transport` when trying to find the ip of the remote_host, we will look for it by trying each value in `ssh_address_locations`.

So instead of getting all IPs possible, we only get the ones the user has told us to.  And once we find the first viable one, we stop there.  This makes `ssh_address_locations` an ordered list of places to look for an ip address to try and use for SSHing into the remote host.

**Comment by bdangit** [comment]
makes sense. let me try a first cut at this.

**Comment by bdangit** [comment]
Hi @tyler-ball -- just want to let you know that I'm still working on this.  Summer vacations and just transitioned into a new team have made development on this really slow.

**Comment by tyler-ball** [comment]
:+1: Thanks for the update!  I've also been busy with real life stuff too, so no worries

**Comment by bdangit** [comment]
@tyler-ball / @jkeiser: finally got this change in.  let me know what you think?

A few notes:
1. Looks like gracefully handling "find_floating_ips" has been taken care of. :smile: 
2. I did some local testing and would love to add to the existing spec, but it appears broken :cry:  This is how I manually tested it below:

```ruby
def parse_ssh_address_locations(machine_spec, server)
  remote_host = ''
  locations = ssh_address_locations?(machine_spec) ? machine_spec['ssh_address_locations'] : ['public_ip_address', 'private_ip_address']
  locations.each do |location|
    case location
    when 'public_ip_address'
      remote_host = server['public_ip_address']
    when 'private_ip_address'
      remote_host = server['private_ip_address']
    when 'ip_addresses'
      # just grab the first one
      remote_host = server['ip_addresses'].first
    else
      raise "Invalid 'ssh_address_locations'.  They can only be 'public_ip_address', 'private_ip_address', and/or 'ip_addresses'."
    end
    # go to next option only if the host is nil or empty
    break unless remote_host.nil? || remote_host.empty?
  end
  remote_host
end

def ssh_address_locations?(machine_spec)
  ssh_address_locations = machine_spec['ssh_address_locations'].reject { |l| l.empty? }
  not ssh_address_locations.nil? || ssh_address_locations.empty?
end

# Default, with every ip type
machine_spec = {}
machine_spec['ssh_address_locations'] = ['']
server = {}
server['public_ip_address'] = '1.1.1.1'
server['private_ip_address'] = '2.2.2.2'
server['ip_addresses'] = ['3.3.3.3', '4.4.4.4']

parse_ssh_address_locations(machine_spec, server)
# 1.1.1.1

# Default, with no public_ip_address
machine_spec = {}
machine_spec['ssh_address_locations'] = ['']
server = {}
server['public_ip_address'] = ''
server['private_ip_address'] = '2.2.2.2'
server['ip_addresses'] = ['3.3.3.3', '4.4.4.4']

parse_ssh_address_locations(machine_spec, server)
# 2.2.2.2

# Default, with no priv/pub
machine_spec = {}
machine_spec['ssh_address_locations'] = ['']
server = {}
server['public_ip_address'] = ''
server['private_ip_address'] = ''
server['ip_addresses'] = ['3.3.3.3', '4.4.4.4']

parse_ssh_address_locations(machine_spec, server)
# ""

# private_ip_address, with every ip type
machine_spec = {}
machine_spec['ssh_address_locations'] = ['private_ip_address']
server = {}
server['public_ip_address'] = '1.1.1.1'
server['private_ip_address'] = '2.2.2.2'
server['ip_addresses'] = ['3.3.3.3', '4.4.4.4']

parse_ssh_address_locations(machine_spec, server)
# 2.2.2.2

# private_ip_address, but not avail
machine_spec = {}
machine_spec['ssh_address_locations'] = ['private_ip_address']
server = {}
server['public_ip_address'] = '1.1.1.1'
server['private_ip_address'] = ''
server['ip_addresses'] = ['3.3.3.3', '4.4.4.4']

parse_ssh_address_locations(machine_spec, server)
# ""

# ip_addresses, with every ip type
machine_spec = {}
machine_spec['ssh_address_locations'] = ['ip_addresses']
server = {}
server['public_ip_address'] = '1.1.1.1'
server['private_ip_address'] = '2.2.2.2'
server['ip_addresses'] = ['3.3.3.3', '4.4.4.4']

parse_ssh_address_locations(machine_spec, server)
# 3.3.3.3

# different order, first option not aval
machine_spec = {}
machine_spec['ssh_address_locations'] = ['ip_addresses', 'private_ip_address', 'public_ip_address']
server = {}
server['public_ip_address'] = '1.1.1.1'
server['private_ip_address'] = '2.2.2.2'
server['ip_addresses'] = []

parse_ssh_address_locations(machine_spec, server)
# 2.2.2.2

# invalid option
machine_spec = {}
machine_spec['ssh_address_locations'] = ['asdf']
server = {}
server['public_ip_address'] = '1.1.1.1'
server['private_ip_address'] = '2.2.2.2'
server['ip_addresses'] = ['3.3.3.3', '4.4.4.4']

parse_ssh_address_locations(machine_spec, server)
# Runtime error error
```

**Comment by tyler-ball** [comment]
Hey @bdangit - thanks for the update on this!  It turns out I made a [similar PR](https://github.com/chef/chef-provisioning-aws/pull/269) for chef-provisioning-aws.  Based upon that I have a few style notes:

1.  Can you use `transport_address_locations` instead of `ssh_address_locations`?  That way we can extend it to support WinRM in the future without renaming it then.
1.  We only want to warn once per chef-client run.  Will you copy the pattern from https://github.com/chef/chef-provisioning-aws/blob/83e84d3bc40454ebbef027da3d6673260961b937/lib/chef/provisioning/aws_driver/driver.rb#L504-L514 to see how I used a variable to store whether we had warned or not yet?
1.  Because we're deprecating the old `use_private_ip_for_ssh` value, can you also copy the pattern from https://github.com/chef/chef-provisioning-aws/blob/83e84d3bc40454ebbef027da3d6673260961b937/lib/chef/provisioning/aws_driver/driver.rb#L860-L865 to remove it from an existing machine spec if we find it there?  That also shows the logic for still using that deprecated config from inside the `determine_remote_host` method.
1.  We also no longer need to store the `use_private_ip_for_ssh` variable into the machine spec because it is deprecated.
1.  It would be nice to support symbols or strings in the array for `transport_address_locations`.  This could be done by modifying https://github.com/bdangit/chef-provisioning-fog/blob/add-no-network/lib/chef/provisioning/fog_driver/driver.rb#L728-L731 to look like
```ruby
def ssh_address_locations(machine_spec)
  ssh_address_locations = [machine_spec.reference['transport_address_locations']].flatten.map &:to_s
end
```
This will normalize the `transport_address_locations` by turning it into an array if it isn't already one, then converting any possible symbols to strings.

Let me know if you need any help with this.

**Comment by bdangit** [comment]
@tyler-ball thanks for the review.  I should have the changes this week.

**Comment by tyler-ball** [comment]
Thanks for your contribution @bdangit!  Sorry this review is taking so long - I think after I [originally suggested](https://github.com/chef/chef-provisioning-fog/pull/96#issuecomment-101429868) `ssh_address_locations` I paged it out of my memory but the ghost of it was still hanging around when I did https://github.com/chef/chef-provisioning-aws/pull/269.  So thanks for continuing to update

**Comment by bdangit** [comment]
@tyler-ball should we allow the concept of allowing users to specify all the types of addresses to find a valid ip?  Or should we just contrain them just to search for one type of address.  So far, there is only `private_ip`, `public_ip`, and `ip_addresses`

**Comment by tyler-ball** [comment]
I am ambivalent about whether we allow users to specify an ordered array of address to try or just one value.

The reason I originally suggested an array here is because thats how we handle it in Test Kitchen.  But you are correct, in my PR I only accept 1 value because I expect the user to know how their network is setup and whether the instance will have a public IP or only a private one.

I am ambivalent on whether we accept an array here or only a single value.  You already have the code for an array (and it gives a user more flexibility).  So I am leaning towards leaving it an array.

What I _really_ care about is that specifying `:transport_address_locations => :private_ip` and `:transport_address_locations => [:private_ip]` do the same thing.

**Comment by bdangit** [comment]
okay and more question, this gem will support "plural" version of `transport_address_location`, meaning the parameter will be `transport_address_locations` compared to singular form `transport_address_location` in AWS gem.  If this is the case, then if we go with a simple recipe that builds infrastructure, a user would have to make some if/else logic in that recipe to support AWS's version compared to FOG's version.

Should we just make the parameter uniform/standardized?  

I think what I am leaning towards is the first version will be more constrained.  Later revisions if necessary we can support having an array of preferred locations to iterate through.

**Comment by tyler-ball** [comment]
@bdangit We're steadily moving away from the example of 'provision AWS and in Vagrant using the same recipe' because it turns out that only works for machines.  Infrastructure topologies are too complicated to easily be expressed across providers.

Having said that, I am fine with converging on one nomenclature across our code bases.  I like minimizing the number of patterns that we use and making documentation more consistent.  So lets go with `transport_address_location`!

**Comment by bdangit** [comment]
@tyler-ball updated...looks cleaner.

**Comment by bdangit** [comment]
@tyler-ball don't merge this yet.  I was able to get some specs running last night by coping what you had here (https://github.com/chef/chef-provisioning-aws/blob/master/spec/unit/chef/provisioning/aws_driver/driver_spec.rb) and there's 2 tests that failed.  

```ruby
rspec ./spec/unit/chef/provisioning/fog_driver/driver_spec.rb:45 # Chef::Provisioning::FogDriver::Driver#determine_remote_host when machine_spec.reference does not specify the transport type when the machine does not have a public_ip_address returns the private ip
rspec ./spec/unit/chef/provisioning/fog_driver/driver_spec.rb:61 # Chef::Provisioning::FogDriver::Driver#determine_remote_host when machine_spec.reference does not specify the transport type when the machine does not have a public_ip_address or private_ip_address raises an error
```

I'll submit another update.

**Comment by bdangit** [comment]
also -- noticed methods in `-aws` gem aren't protected but these are... i'll need to figure out how to test methods in protected mode.

**Comment by bdangit** [comment]
@tyler-ball updated and corrected functionality for `transport_address_location`.

**Comment by tyler-ball** [comment]
@bdangit you can just remove the `protected` keyword.  It doesn't work the way we thought it did

**Comment by tyler-ball** [comment]
@bdangit The PR ended up much cleaner - and you got test coverage!  Thanks for all the work on this

**Comment by bdangit** [comment]
@tyler-ball cool! anytime.  Is there an ETA of when 0.14.0 will be released?

**Comment by tyler-ball** [comment]
There is not - but there is going to be a big wave of releases coming, starting with Chef Provisioning 1.4.0.  Its on my TODO list but I need to look at the open issues and scope what I want to get in before I release.  Its already pretty big, so it probably won't be anything that isn't super high priority

**Pull request merged**
