### PR TITLE
Vcair changes

### PR DESCRIPTION
**Pull request by monkey1016**
I updated the vcair driver in the hopes of getting it working better with vCloud Director.  I tried to make it similar to [chef-provisioning-vra](https://github.com/chef-partners/chef-provisioning-vra), but I understand that it changes how the vcair driver works compared to the other fog drivers.

I've switched it from using knife configuration options to use `driver_options` and made some changes to the driver url.  If it doesn't mesh well, let me know.  I'd appreciate the feedback.

If it looks good, I can provide documentation for the changes.

### CODE REVIEW

**Comment by jjasghar** [comment]
With our new policy please use the [DCO signing process](https://discourse.chef.io/t/a-developer-certificate-of-origin-dco-is-now-required-with-code-contributions/9579).

For a [detailed description](http://stackoverflow.com/questions/13457203/how-to-add-the-signed-off-by-field-in-the-git-patch) or you can just do:

```
$ git commit -s
$ #Or
$ git commit --signoff
```

If you already have the commit, use `git commit --amend` or `git rebase -i` to edit your commit message, and add the above signoff line.

Or if you want a more perminant option the following is a way to set it forever:

```bash
$ git config commit.gpgsign true
```

**Comment by monkey1016** [comment]
Sorry about that.  I signed the commit.

**Comment by jjasghar** [comment]
Looks good. I would like someone else to 👍  that uses vcair before merging/releasing.

As soon as that happens I'll update the gem.

**Comment by jjasghar** [comment]
@monkey1016 awesome, thanks for all this. I don't have the expertise in vcair to say if this works or not. If we can get someone to comment and say that it's good, i'm willing to release this. 

Thanks for making `chef-provisioning-fog` more delightful!

**Comment by monkey1016** [comment]
Looks like a change to the `cheffish` gem (v4.1.0) caused the tests to start failing for the Rackspace provider.  I downgraded to `cheffish` v4.0.0 and everything started working again.
See [failing build](https://travis-ci.org/chef/chef-provisioning-fog/jobs/194821697) vs [working build](https://travis-ci.org/chef/chef-provisioning-fog/jobs/191466224)

**Comment by monkey1016** [comment]
Hi,
Any chance we can merge this into the repo so we can get a released version of the gem?  There don't seem to be many users of vCloud Director or vCloud Air.  Or maybe fork to a separate gem if there's no intention on supporting vCloud?
I suspect if we wait for a someone else to say it works, we'll be waiting for a long, long time.

**Comment by jjasghar** [comment]
thanks for all this work, i've gone ahead and released v0.22.0 of this gem. 🤘

**Comment by monkey1016** [comment]
Awesome!  Thanks.  I'll create another pull request for some docs too.  Been meaning to do that too.

**Comment by jjasghar** [comment]
Perfect! Thanks!

**Pull request merged**
