### PR TITLE
Solve NoMethodError for fog providers that do not provide the 'addresses' method to the 'server' object

### PR DESCRIPTION
**Pull request by SIGUSR2**
see https://apidocs.joyent.com/cloudapi/#CreateMachine

### CODE REVIEW

**Comment by jkeiser** [comment]
Thanks for getting this!  The solution here is for this is to override the method in https://github.com/chef/chef-provisioning-fog/blob/master/lib/chef/provisioning/fog_driver/providers/joyent.rb:

```ruby
def find_floating_ips(server)
  []
end
```

Terribly sorry for the late review, post-ChefConf madness destroyed my availability for a bit.

**Comment by SIGUSR2** [comment]
@jkeiser No problem. I made the change(s) in my repo, guess it may be merged now.

**Comment by hulu1522** [comment]
Associated with issue #118

**Comment by randomcamel** [comment]
LGTM.

**Comment by randomcamel** [comment]
@SIGUSR2 Seems odd that this works when the signature doesn't match the superclass method:

    def find_floating_ips(server, action_handler)

But if it works, it works.

**Comment by SIGUSR2** [comment]
@randomcamel It probably does not. This PR was made when the method had only one argument. Fix added. Hope it will be merged before the method ends up having 3 or more arguments.

**Comment by randomcamel** [comment]
@SIGUSR2 Touché.

**Comment by SIGUSR2** [comment]
@randomcamel Thanks :)

**Pull request merged**
