### PR TITLE
Fix for Chef-13/ChefDK2/Cheffish 5.x/13.x, removal of fog mega-gem

### PR DESCRIPTION
**Pull request by lamont-granquist**
only trying to fix cheffish now

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
yep still busted on the two busted specs

**Comment by icco** [comment]
I would recommend not requiring fog at all, and just require the sub-projects (i.e. fog-google).

**Comment by lamont-granquist** [comment]
well this is more about just figuring out what we need to fix chef-provisioning-fog for cheffish 5.x/13.x where the MergedConfig API changed.

master is currently red and broken for reasons unrelated to fog at all.

at the same time, that seems like a good idea on the face of it, but my knowledge of fog is probably 5 years out of date.

it looks like fog-google pulls in fog-core, presumably other plugins do as well -- and is `fog` just there for some kind of mega-pull-it-all-in-backcompat-reasons?

**Comment by lamont-granquist** [comment]
there's also sort of the problem where we don't know what plugins people are actually using

**Comment by icco** [comment]
Yeah, fog exists for legacy reasons. It's also got some weird dependencies because it supports old rubies

**Pull request merged**
