### PR TITLE
update for latest gems

### PR DESCRIPTION
**Pull request by lamont-granquist**

### CODE REVIEW

**Comment by tas50** [comment]
The google gem entirely breaks the API and requires some rework here

**Comment by lamont-granquist** [comment]
i'm not entirely certain that i even care about fixing that before shipping?  and certainly not before merging.   the choo-choo train needs to start moving here, or we just need to light this repo on fire and abandon it entirely and move it to chef-boneyard.

**Comment by tas50** [comment]
Just pointing out why I didn't do this months ago. We need to fix it or abandon it. I'm indifferent on the whole thing.

**Comment by lamont-granquist** [comment]
Well, this is better.

Travis is busted, but that is entirely accurate, because this project is busted.  Needs fixing before shipping.

**Comment by tas50** [comment]
We need this to get merged into fog https://github.com/fog/fog-google/pull/210

**Pull request merged**
