### PR TITLE
Update to current Fog call to assign IP

### PR DESCRIPTION
**Pull request by thommay**
Ensure that we can actually attach IPs to OpenStack instances

### CODE REVIEW

**Comment by ncerny** [comment]
We ran into this issue today while trying to assign a floating IP from a pool.  The call passes 2 parameters, and the method expects 3.  This PR would fix that issue, so I'd like to see it merged.

+1

**Comment by rduppen** [comment]
+1 to ncerny's request
btw, I would like to add that we ran into a race condition when attaching the floating ip, OpenStack didn't know yet about our machine when attempting to attach it. giving the following exception:
```
BadRequest: No nw_info cache associated with instance (HTTP 400) 
```
we've fixed it using a sleep in attach_floating_ips, but that's kindy quick an dirty

**Comment by ryancragun** [comment]
:+1:

**Comment by jkeiser** [comment]
@ryancragun @ncerny @rduppen I just pushed a further change to localize this fix to OpenStack.  Can you verify whether it works for you?  If it does, we'll merge.  The issue was risk to the AWS part of the driver.

**Comment by tyler-ball** [comment]
Closing this in favor of https://github.com/chef/chef-provisioning-fog/pull/86 - please move all conversation there!

**Pull request closed without merging**
