### PR TITLE
Added rubygems deployment

### PR DESCRIPTION
**Pull request by jjasghar**
- Per customer request added the ability for travis to deploy to
  rubygems.

### CODE REVIEW

**Comment by jjasghar** [comment]
Enabling on TAGs releases via: http://docs.travis-ci.com/user/deployment/rubygems/

**Comment by tyler-ball** [comment]
Lets do this - setup a Rake command that does the following:

1. Bumps the `version.rb` patch version (there are gems that can handle this for us)
2. Runs `github_changelog_generator` to update the CHANGELOG.rb per the release guide
3. Commits those as a change to master (`git commit -am "Preparing the #{future_version} release" && git push`)
4. Runs git tag to take the release (`git tag -a "Releasing #{future_version}" && git push --tags`)

Combined with the Travis change, this gives users a single command to perform a release

**Comment by bdangit** [comment]
cool!

**Comment by jjasghar** [comment]
@bdangit I'd like to say i havent forgotten about this. I've just been caught up in my openstack duties. I'll get to this ASAP. Though if you want to make the `rake` task for me i wouldn't object. :metal:

**Comment by bdangit** [comment]
yo @jj got the note. End of year commitments are preventing me from working fast on this. :)

I should have something next week.

**Comment by jjasghar** [comment]
https://github.com/chef/chef-provisioning-fog/pull/152 will take care of the Rake task when merged.

**Pull request merged**
